name: Lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  spotless:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check formatting
        run: |
          chmod +x gradlew
          ./gradlew spotlessCheck
